-- 1 COMANDO PARA CRIAR BANCO DE DADOS
create database Smart_Coffee_Luis;

-- 1.2 COMANDO PARA CRIAR BANCO DE DADOS CASO (IF) NÃO (NOT) EXISTA (EXISTS)
CREATE DATABASE IF NOT EXISTS Smart_Coffee_Luis;

-- 1.3 Comando para apagar o banco de dados
drop database Smart_Coffee_Luis; 

-- 2 ATIVAR O BANCO DE DADOS 
USE Smart_Coffee_Luis;

-- 3 CRIAR TABELAS

CREATE TABLE  Funcionario (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
CARGO VARCHAR(30) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME_FUNCIONARIO VARCHAR(250) NOT NULL,
NACIONALIDADE VARCHAR(250),
DATA_NASCIMENTO DATE,
EMAIL VARCHAR(60) NOT NULL,
DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE  CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME_CLIENTE VARCHAR(250) NOT NULL,
NACIONALIDADE VARCHAR(250),
DATA_NASCIMENTO DATE,
EMAIL VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(17) NOT NULL,
DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE  PLANO_DE_FIDELIDADE (
ID_FIDELIDADE INT AUTO_INCREMENT PRIMARY KEY,
NIVEL_CLIENTE INT(90),
QUANTIDADE_PONTOS INT(90),
STATUS_PLANO ENUM ("ATIVO", "DESATIVO") DEFAULT "ATIVO",
VALIDADE_PONTOS BOOLEAN DEFAULT TRUE,
DATA_ADESAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PEDIDO (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
VALOR_TOTAL DECIMAL(20, 2) DEFAULT 0.00,
OBSERVACAO VARCHAR(250),
TIPO_PEDIDO VARCHAR(30) NOT NULL,
STATUS_PEDIDO ENUM ("ATIVO", "DESATIVO") DEFAULT "DESATIVO"
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
METODO_PAGAMENTO ENUM ("CREDITO", "DEBITO", "PIX"),
STATUS_PEDIDO ENUM ("ATIVO", "DESATIVO"),
VALOR_PAGO DECIMAL(20, 2) DEFAULT 0.00
);

CREATE TABLE DELIVERY (
ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
NUMERO INT(10) NOT NULL,
ENDERECO VARCHAR(250) NOT NULL,
TAXA_ENTREGA INT(20) NOT NULL,
STATUS_ENTREGA ENUM ("ENTREGUE", "NAO ENTREGUE") DEFAULT "NAO ENTREGUE",
PREVISAO_ENTREGA datetime
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PRODUTO VARCHAR(90) NOT NULL,
TAMANHO VARCHAR(20) NOT NULL,
DISPONIVEL ENUM ("SIM", "NAO") DEFAULT "NAO",
DESCRICAO VARCHAR(150) NOT NULL,
PESO VARCHAR(4) NOT NULL,
PRECO INT(10) NOT NULL
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA VARCHAR(90) NOT NULL,
DESCRICAO VARCHAR(150) NOT NULL,
CODIGO VARCHAR(12) NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TIPO VARCHAR(15) NOT NULL
);

CREATE TABLE FORNECEDOR (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOME_FORNECEDOR	VARCHAR(90),
STATUS_FORNECIMENTO ENUM ("ENTREGUE", "NAO ENTREGUE") DEFAULT "NAO ENTREGUE",
DATA_FORNECIDA DATETIME,
TIPO_ENTREGA ENUM ("CARGA", "CAMINHAO"),
TELEFONE VARCHAR(17) NOT NULL,
CPNJ VARCHAR(14) NOT NULL
);

CREATE TABLE ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE_MAXIMA VARCHAR(40) NOT NULL,
QUANTIDADE_MINIMA VARCHAR(20) NOT NULL,
UNIDADE_MEDIDA VARCHAR(15) NOT NULL,
ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
QUANTIDADE_ATUAL INT(30) NOT NULL
);








