
create database Oficina_Luis;

CREATE DATABASE IF NOT EXISTS Oficina_Luis;


drop database Oficina_Luis; 


USE Oficina_Luis;


CREATE TABLE  Servicos (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
TIPO_SERVICO ENUM ("MANUTENCAO", "PINTURA") NOT NULL DEFAULT "MANUTENCAO",
DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DATA_FINALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
OBSERVACAO_SERVICO VARCHAR(250),
DIAGNOSTICO_SERVICO VARCHAR(120),
VALOR_TOTAL DECIMAL(20, 2) DEFAULT 0.00
);

ALTER TABLE Servicos ADD Erros_Cometidos VARCHAR(100);

ALTER TABLE Servicos DROP COLUMN Erros_Cometidos;

RENAME TABLE Servicos TO modelos_fab; 

CREATE TABLE  Clientes (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(60) NOT NULL,
CPF_CLIENTE VARCHAR(14) NOT NULL UNIQUE,
TELEFONE_CLIENTE VARCHAR(14) not null,
DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NACIONALIDADE VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);

ALTER TABLE Clientes ADD Idade Int;

ALTER TABLE Clientes DROP COLUMN Idade;



CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF_FUNCIONARIO VARCHAR(14) NOT NULL UNIQUE,
TELEFONE_FUNCIONARIO VARCHAR(14) NOT NULL,
DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Turno VARCHAR(50) NOT NULL,
Funcao_Funcionario VARCHAR(30) NOT NULL
);

ALTER TABLE Funcionarios ADD Idade Int;

ALTER TABLE Funcionarios DROP COLUMN Idade;



CREATE TABLE VEICULOS (
ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
TIPO_VEICULO ENUM ("MOTO", "CARRO") NOT NULL DEFAULT "CARRO",
DATA_CHEGADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DATA_SAIDA DATE NOT NULL,
OBSERVACOES_VEICULO VARCHAR(250) NOT NULL,
ESTADO_VEICULO ENUM ("CRITICO", "SIMPLES") NOT NULL DEFAULT "SIMPLES"
);

ALTER TABLE Veiculos ADD Tempo_Uso Int;

ALTER TABLE Veiculos DROP COLUMN Tempo_Uso;



CREATE TABLE MARCAS (
ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TIPO_VEICULOS VARCHAR(30) NOT NULL DEFAULT "CARROS ou MOTOS",
NACIONALIDADE VARCHAR(50) NOT NULL,
PARCERIA ENUM ("SIM", "NAO") NOT NULL DEFAULT "NAO",
TELEFONE_MARCA VARCHAR(14) NOT NULL,
CNPJ_MARCA VARCHAR(20) NOT NULL,
nome_marca varchar(30) not null
);

ALTER TABLE Marcas ADD Email VARCHAR(60) NOT NULL;

ALTER TABLE Marcas DROP COLUMN Email;



CREATE TABLE MODELOS (
ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
NOME_MODELO VARCHAR(60) NOT NULL,
TIPO_MOTOR ENUM ("ELETRICO", "COMBUSTAO") NOT NULL DEFAULT "COMBUSTAO",
LINK_MANUAL VARCHAR(50) NOT NULL,
PROBLEMAS_CRONICOS TEXT NOT NULL,
Observacoes_Modelo Varchar(250)
);

ALTER TABLE Modelos ADD Tipo_Pneu VARCHAR(60) NOT NULL;

ALTER TABLE Modelos DROP COLUMN Tipo_Pneu;





CREATE TABLE PECAS (
ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TAMANHO_PECA INT NOT NULL,
PESO_PECA INT NOT NULL,
CUSTO_PECA INT NOT NULL,
NOME_PECA VARCHAR(60) NOT NULL
);

ALTER TABLE Pecas ADD Garantia_Anos Int NOT NULL;

ALTER TABLE Pecas DROP COLUMN Garantia_Anos;



CREATE TABLE FORNECEDORES (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
TIPO_ENTREGA ENUM("CAMINHAO", "CARGUEIRO") NOT NULL DEFAULT "CAMINHAO",
NACIONALIDADE VARCHAR(50) NOT NULL,
TELEFONE_FORNECEDOR VARCHAR(14) NOT NULL,
DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CNPJ_FORNECEDOR VARCHAR(20) NOT NULL
);

ALTER TABLE Fornecedores ADD Email VARCHAR(60) NOT NULL;

ALTER TABLE Fornecedores DROP COLUMN Email;



CREATE TABLE ORDENS_DE_SERVICO (
ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
PRIORIDADE ENUM ("URGENTE", "SIMPLES") NOT NULL DEFAULT "SIMPLES",
PRAZO_FINAL DATE NOT NULL,
RANKING_ORDEM VARCHAR(40) NOT NULL,
DATA_EMISSAO TIMESTAMP DEFAULT current_timestamp,
TIPO_CASO VARCHAR(30) NOT NULL

);

ALTER TABLE Ordens_De_Servico ADD Area_Servico VARCHAR(60) NOT NULL;

ALTER TABLE Ordens_De_Servico DROP COLUMN Area_Servico;

 

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
STATUS_PAGAMENTO ENUM ("APROVADO", "NEGADO") NOT NULL DEFAULT "NEGADO",
PARCELAS INT NOT NULL,
VALOR_PAGO DECIMAL(20, 2) DEFAULT 0.00,
DATA_EMISSAO TIMESTAMP DEFAULT current_timestamp,
TIPO_PAGAMENTO VARCHAR(35) NOT NULL

);

ALTER TABLE Pagamento ADD Observacoes_Pagamento VARCHAR(250) NOT NULL;

ALTER TABLE Pagamento DROP COLUMN Observacoes_Pagamento;




