-- CR = Cardinalidade e Relacionamento

CREATE DATABASE if not EXISTS SESI_CR_TB;

drop DATABASE SESI_CR;

use SESI_CR_TB;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PEDIDO DATETIME NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

SELECT * FROM cliente;

SELECT * FROM pedido;

INSERT INTO
    CLIENTE (NOME_CLIENTE)
VALUES ('BRUNO'),
    ('MARTA'),
    ('JOSÉ');