-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE TABLE Cliente (
    Nome_Cliente VarChar(90) NotNull,
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY
)

CREATE TABLE Pedido (
    Data_Pedido DateTime Not null,
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente (ID_CLIENTE)
)

CREATE TABLE Estoque (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(60) NOT NULL,
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID_PRODUTO, ID_ESTOQUE)
)

CREATE TABLE Fornecedor (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL
)

CREATE TABLE Produto (
    id_produto INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    NOME_PRODUTO VARCHAR(90) NOT NULL
)

CREATE TABLE Cliente (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    cpf varchar(19) not null,
    ID_pedido INT NOT NULL /*falha: chave estrangeira*/
)

CREATE TABLE Pedido (
    ID_pedido INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    Data_Pedido DATETIME NOT NULL
)

CREATE TABLE Relação_3 + Item Pedido (
    ID_FORNECEDOR INT NOT NULL,
    id_produto INT NOT NULL,
    Id_Item INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
    Valor Decimal(10, 2) not null
)